version: "3.1"

services:
  db:
    hostname: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./database/data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./database/seed
        target: /docker-entrypoint-initdb.d
